- 👋 Hi, I’m @Aquiz25
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
Aquiz25/Aquiz25 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
Hi I'm Aquiz25, I'm interested in learning software engineering and I'm looking to collaborate with you and you can reach me on ezebolingochukwu@gmail.com
